name: Deploy to VM Instance

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage
          
      - name: Run Tests
        run: |
          echo "Starting tests"
          coverage erase
          coverage run --include="./*/*" --omit="./env/*,./project/*,./manage.py,./templates/*,./static/*" manage.py test .
          coverage xml -i
          coverage report -m

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Connecting to the VM and deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Attach to the screen session and stop main.py
            screen -S spongeweb -X quit
            
            # Navigate to the codebase directory (update this path)
            cd ~/spongeweb
            
            # Update the codebase
            git pull
            
            # Restart the python program in screen
            screen -dmS spongeweb python3 manage.py runserver 0.0.0.0:8000